const meleeWeapons = [
  {
    Name: "Barbed Dagger",
    Cost: "10 gp",
    Damage: "2d4",
    Damagetype: "Piercing",
    Weight: "1 lb",
    Homebrew: "True",
    Properties: ["Light", "Finesse", "Thrown (20/60)"],
  },
  {
    Name: "Brandistock",
    Cost: "10 gp",
    Damage: "1d8",
    Damagetype: "Piercing",
    Weight: "4 lb",
    Homebrew: "True",
    Properties: ["Special", "Two-handed"],
  },
  {
    Name: "Broken Sword",
    Cost: "5 sp",
    Damage: "1d4",
    Damagetype: "Piercing",
    Weight: "1 lb",
    Homebrew: "True",
    Properties: ["Light", "Finesse"],
  },
  {
    Name: "Cestus",
    Cost: "5 sp",
    Damage: "1d4",
    Damagetype: "Bludgeoning",
    Weight: "0.5 lb",
    Homebrew: "True",
    Properties: ["Light", "Special"],
  },
  {
    Name: "Club",
    Cost: "1 sp",
    Damage: "1d4",
    Damagetype: "Bludgeoning",
    Weight: "2 lb",
    Homebrew: "False",
    Properties: ["Light"],
  },
  {
    Name: "Dagger",
    Cost: "2 gp",
    Damage: "1d4",
    Damagetype: "Piercing",
    Weight: "1 lb",
    Homebrew: "False",
    Properties: ["Light", "Finesse", "Thrown (20/60)"],
  },
  {
    Name: "Double Spear",
    Cost: "5 gp",
    Damage: "1d6",
    Damagetype: "Piercing",
    Weight: "4 lb",
    Homebrew: "True",
    Properties: ["Versatile (1d8)", "Thrown (20/60)"],
  },
  {
    Name: "Eye Sickle",
    Cost: "10 gp",
    Damage: "1d6",
    Damagetype: "Piercing",
    Weight: "4 lb",
    Homebrew: "True",
    Properties: ["Light", "Finesse"],
  },
  {
    Name: "Falx",
    Cost: "8 gp",
    Damage: "1d6",
    Damagetype: "Slashing",
    Weight: "3 lb",
    Homebrew: "True",
    Properties: ["Versatile (1d8)"],
  },
  {
    Name: "Fauchard",
    Cost: "10 gp",
    Damage: "1d6",
    Damagetype: "Slashing",
    Weight: "7 lb",
    Homebrew: "True",
    Properties: ["Heavy", "reach", "Two-handed"],
  },
  {
    Name: "Flamberge",
    Cost: "15 gp",
    Damage: "1d8 + 1d2",
    Damagetype: "Slashing + Ripping",
    Weight: "6 lb",
    Homebrew: "True",
    Properties: ["Ripping", "Two-handed"],
  },
  {
    Name: "Gavel",
    Cost: "5 sp",
    Damage: "1d4",
    Damagetype: "Bludgeoning",
    Weight: "0.5 lb",
    Homebrew: "True",
    Properties: ["Undersized"],
  },
  {
    Name: "Greatclub",
    Cost: "2 sp",
    Damage: "1d8",
    Damagetype: "Bludgeoning",
    Weight: "10 lb",
    Homebrew: "False",
    Properties: ["Two-handed"],
  },
  {
    Name: "Greatspear",
    Cost: "25 gp",
    Damage: "1d10",
    Damagetype: "Piercing",
    Weight: "8 lb",
    Homebrew: "True",
    Properties: ["Oversized", "Thrown (20/60)", "Two-handed"],
  },
  {
    Name: "Handaxe",
    Cost: "5 gp",
    Damage: "1d6",
    Damagetype: "Slashing",
    Weight: "2 lb",
    Homebrew: "False",
    Properties: ["Light", "Thrown (20/60)"],
  },
  {
    Name: "Iron Claws",
    Cost: "5 gp",
    Damage: "1d4",
    Damagetype: "Piercing",
    Weight: "2 lb",
    Homebrew: "True",
    Properties: ["Light", "Finesse"],
  },
  {
    Name: "Javelin",
    Cost: "5 sp",
    Damage: "1d6",
    Damagetype: "Piercing",
    Weight: "2 lb",
    Homebrew: "False",
    Properties: ["Thrown (30/120)"],
  },
  {
    Name: "Karambit",
    Cost: "4 gp",
    Damage: "1d4",
    Damagetype: "Slashing",
    Weight: "1 lb",
    Homebrew: "True",
    Properties: ["Light", "Finesse"],
  },
  {
    Name: "Katar",
    Cost: "5 gp",
    Damage: "1d4",
    Damagetype: "Piercing",
    Weight: "1 lb",
    Homebrew: "True",
    Properties: ["Light", "Finesse"],
  },
  {
    Name: "Knife",
    Cost: "2 sp",
    Damage: "1d3",
    Damagetype: "Slashing",
    Weight: "0.25 lb",
    Homebrew: "True",
    Properties: ["Undersized", "Finesse"],
  },
  {
    Name: "Knuckleduster",
    Cost: "3 sp",
    Damage: "Unarmed Damage + 1",
    Damagetype: "",
    Weight: "2 lb",
    Homebrew: "True",
    Properties: ["Light", "Special"],
  },
  {
    Name: "Ko",
    Cost: "1 gp",
    Damage: "1d4",
    Damagetype: "Piercing / bludgeoning",
    Weight: "1 lb",
    Homebrew: "True",
    Properties: ["Light", "Finesse", "Special"],
  },
  {
    Name: "Kukri",
    Cost: "6 gp",
    Damage: "1d6",
    Damagetype: "Slashing",
    Weight: "2 lb",
    Homebrew: "True",
    Properties: ["Light", "Thrown (20/60)"],
  },
  {
    Name: "Light Hammer",
    Cost: "2 gp",
    Damage: "1d4",
    Damagetype: "Bludgeoning",
    Weight: "2 lb",
    Homebrew: "False",
    Properties: ["Light", "Thrown (20/60)"],
  },
  {
    Name: "Mace",
    Cost: "5 gp",
    Damage: "1d6",
    Damagetype: "Bludgeoning",
    Weight: "2 lb",
    Homebrew: "False",
    Properties: [],
  },
  {
    Name: "Needle",
    Cost: "2 sp",
    Damage: "1d4",
    Damagetype: "Piercing",
    Weight: "0.25 lb",
    Homebrew: "True",
    Properties: ["Undersized", "Finesse"],
  },
  {
    Name: "Quarterstaff",
    Cost: "2 sp",
    Damage: "1d6",
    Damagetype: "Bludgeoning",
    Weight: "4 lb",
    Homebrew: "False",
    Properties: ["Versatile (1d8)"],
  },
  {
    Name: "Sap",
    Cost: "1 gp",
    Damage: "1d4",
    Damagetype: "Bludgeoning",
    Weight: "2 lb",
    Homebrew: "True",
    Properties: ["Light", "Finesse"],
  },
  {
    Name: "Scythe",
    Cost: "5 gp",
    Damage: "2d4",
    Damagetype: "Slashing",
    Weight: "5 lb",
    Homebrew: "True",
    Properties: ["Heavy", "Two-handed"],
  },
  {
    Name: "Sickle",
    Cost: "1 gp",
    Damage: "1d4",
    Damagetype: "Slashing",
    Weight: "2 lb",
    Homebrew: "False",
    Properties: ["Light"],
  },
  {
    Name: "Spade",
    Cost: "2 gp",
    Damage: "1d4",
    Damagetype: "Bludgeoning",
    Weight: "4 lb",
    Homebrew: "True",
    Properties: ["Versatile"],
  },
  {
    Name: "Spear",
    Cost: "1 gp",
    Damage: "1d4",
    Damagetype: "Slashing",
    Weight: "3 lb",
    Homebrew: "False",
    Properties: ["Thrown (20/60)", "Versatile (1d8)"],
  },
  {
    Name: "Torch Mace",
    Cost: "6 gp",
    Damage: "1d4",
    Damagetype: "Bludgeoning",
    Weight: "2 lb",
    Homebrew: "True",
    Properties: ["Special"],
  },
  {
    Name: "Torch Staff",
    Cost: "12 gp",
    Damage: "2d4",
    Damagetype: "Bludgeoning",
    Weight: "7 lb",
    Homebrew: "True",
    Properties: ["Heavy", "Two-handed", "Special"],
  },
  {
    Name: "Zerka",
    Cost: "10 sp",
    Damage: "1d8",
    Damagetype: "Piercing",
    Weight: "3 lb",
    Homebrew: "True",
    Properties: ["Special", "Finesse", "Thrown (40/160)"],
  },
  {
    Name: "Battleaxe",
    Cost: "10 gp",
    Damage: "1d8",
    Damagetype: "Slashing",
    Weight: "4 lb",
    Properties: ["Versatile (1d10)"],
  },
  {
    Name: "Broadsword",
    Cost: "20 gp",
    Damage: "2d4 piercing",
    Damagetype: "Piercing",
    Weight: "3 lb",
    Properties: [],
  },
  {
    Name: "Chain",
    Cost: "8 gp",
    Damage: "1d6 bludgeoning",
    Damagetype: "Bludgeoning",
    Weight: "10 lb",
    Properties: ["Heavy", "Finesse", "Reach", "Special", "Two-Handed"],
  },
  {
    Name: "Cutlass",
    Cost: "10 gp",
    Damage: "1d8 slashing",
    Damagetype: "Slashing",
    Weight: "2 lb",
    Properties: ["Light"],
  },
  {
    Name: "Falchion",
    Cost: "10 gp",
    Damage: "1d8 slashing",
    Damagetype: "Slashing",
    Weight: "3 lb",
    Properties: [],
  },
  {
    Name: "Flail",
    Cost: "10 gp",
    Damage: "1d8 bludgeoning",
    Damagetype: "Bludgeoning",
    Weight: "2 lb",
    Properties: [],
  },
  {
    Name: "Glaive",
    Cost: "20 gp",
    Damage: "1d10 slashing",
    Damagetype: "Slashing",
    Weight: "6 lb",
    Properties: ["Heavy", "Reach", "Two-Handed"],
  },
  {
    Name: "Greataxe",
    Cost: "30 gp",
    Damage: "1d12 slashing",
    Damagetype: "Slashing",
    Weight: "7 lb",
    Properties: ["Heavy", "Two-Handed"],
  },
  {
    Name: "Great Maul",
    Cost: "150 gp",
    Damage: "3d6 bludgeoning",
    Damagetype: "Bludgeoning",
    Weight: "145 lb",
    Properties: ["Oversized", "Two-Handed", "Special"],
  },
  {
    Name: "Greatsword",
    Cost: "50 gp",
    Damage: "2d6 slashing",
    Damagetype: "Slashing",

    Weight: "6 lb",
    Properties: ["Heavy", "Two-Handed"],
  },
  {
    Name: "Guisarme",
    Cost: "15 gp",
    Damage: "2d4 slashing",
    Damagetype: "Slashing",
    Weight: "6 lb",
    Properties: ["Heavy", "Reach", "Two-Handed"],
  },
  {
    Name: "Halberd",
    Cost: "20 gp",
    Damage: "1d10 slashing",
    Damagetype: "Slashing",
    Weight: "6 lb",
    Properties: ["Heavy", "Reach", "Two-Handed"],
  },
  {
    Name: "Heavy Flail",
    Cost: "20 gp",
    Damage: "1d12 bludgeoning",
    Damagetype: "Bludgeoning",
    Weight: "7 lb",
    Properties: ["Heavy", "Two-Handed"],
  },
  {
    Name: "Hidden Blade",
    Cost: "100 gp",
    Damage: "1d4 piercing",
    Damagetype: "Piercing",
    Weight: "0.5 lb",
    Properties: ["Light", "Finesse", "Special"],
  },
  {
    Name: "Katana",
    Cost: "50 gp",
    Damage: "1d8 slashing",
    Damagetype: "Slashing",
    Weight: "3 lb",
    Properties: ["Versatile (1d10)"],
  },
  {
    Name: "Lance",
    Cost: "10 gp",
    Damage: "1d12 piercing",
    Damagetype: "Piercing",
    Weight: "6 lb",
    Properties: ["Reach", "Special"],
  },
  {
    Name: "Longspear",
    Cost: "3 gp",
    Damage: "1d6 piercing",
    Damagetype: "Piercing",
    Weight: "4 lb",
    Properties: ["Heavy", "Reach", "Versatile (1d8)"],
  },
  {
    Name: "Longstaff",
    Cost: "5 sp",
    Damage: "1d8 bludgeoning",
    Damagetype: "Bludgeoning",
    Weight: "7 lb",
    Properties: ["Heavy", "Reach", "Special", "Two-Handed"],
  },
  {
    Name: "Longsword",
    Cost: "15 gp",
    Damage: "1d8 slashing",
    Damagetype: "Slashing",
    Weight: "3 lb",
    Properties: ["Versatile (1d10)"],
  },
  {
    Name: "Main Gauche",
    Cost: "5 gp",
    Damage: "1d4 piercing",
    Damagetype: "Piercing",
    Weight: "1 lb",
    Properties: ["Finesse", "Light", "Special", "Thrown (20/60)"],
  },
  {
    Name: "Man Catcher",
    Cost: "25 gp",
    Damage: "1d4 bludgeoning",
    Damagetype: "Bludgeoning",
    Weight: "2 lb",
    Properties: ["Reach", "Two-Handed", "Special"],
  },
  {
    Name: "Maul",
    Cost: "10 gp",
    Damage: "2d6 bludgeoning",
    Damagetype: "Bludgeoning",
    Weight: "10 lb",
    Properties: ["Heavy", "Two-Handed"],
  },
  {
    Name: "Morningstar",
    Cost: "15 gp",
    Damage: "1d8 piercing",
    Damagetype: "Piercing",
    Weight: "4 lb",
    Properties: [],
  },
  {
    Name: "Pike",
    Cost: "5 gp",
    Damage: "1d10 piercing",
    Damagetype: "Piercing",
    Weight: "18 lb",
    Properties: ["Heavy", "Reach", "Two-Handed"],
  },
  {
    Name: "Rapier",
    Cost: "25 gp",
    Damage: "1d8 piercing",
    Damagetype: "Piercing",
    Weight: "2 lb",
    Properties: ["Finesse"],
  },
  {
    Name: "Pollaxe",
    Cost: "20 gp",
    Damage: "2d4 bludgeoning",
    Damagetype: "Bludgeoning",
    Weight: "6 lb",
    Properties: ["Heavy", "Reach", "Two-Handed"],
  },
  {
    Name: "Saber",
    Cost: "35 gp",
    Damage: "1d8 slashing",
    Damagetype: "Slashing",
    Weight: "3 lb",
    Properties: ["Light", "Finesse"],
  },
  {
    Name: "Scimitar",
    Cost: "25 gp",
    Damage: "1d6 slashing",
    Damagetype: "Slashing",
    Weight: "3 lb",
    Properties: ["Light", "Finesse"],
  },
  {
    Name: "Shortsword",
    Cost: "10 gp",
    Damage: "1d6 piercing",
    Damagetype: "Piercing",
    Weight: "2 lb",
    Properties: ["Light", "Finesse"],
  },
  {
    Name: "Trident",
    Cost: "5 gp",
    Damage: "1d6 piercing",
    Damagetype: "Piercing",
    Weight: "4 lb",
    Properties: ["Thrown (20/60)", "Versatile (1d8)"],
  },
  {
    Name: "Two-Handed Morningstar",

    Cost: "25 gp",
    Damage: "1d12 piercing",
    Damagetype: "Piercing",
    Weight: "10 lb",
    Properties: ["Heavy", "Two-Handed"],
  },
  {
    Name: "War Pick",
    Cost: "5 gp",
    Damage: "1d8 piercing",
    Damagetype: "Piercing",
    Weight: "2 lb",
    Properties: [],
  },
  {
    Name: "War Hammer",
    Cost: "15 gp",
    Damage: "1d8 bludgeoning",
    Damagetype: "Bludgeoning",
    Weight: "2 lb",
    Properties: ["Versatile (1d10)"],
  },

  {
    Name: "Whip",
    Cost: "2 gp",
    Damage: "1d4 slashing",
    Damagetype: "Slashing",
    Weight: "3 lb",
    Properties: ["Reach", "Finesse"],
  },
  {
    Name: "Zweihänder",
    Cost: "100 gp",
    Damage: "2d8 slashing",
    Damagetype: "Slashing",
    Weight: "9 lb",
    Properties: ["Heavy", "Reach", "Special", "Two-Handed"],
  },
];

const rangedWeapons = [
  {
    Name: "Blowgun",
    Cost: "10 gp",
    Damage: "1 piercing",
    Damagetype: "Piercing",
    Weight: "1 lb",
    Properties: ["Ammunition", "Loading"],
  },
  {
    Name: "Crossbow, Hand",
    Cost: "75 gp",
    Damage: "1d6 piercing",
    Damagetype: "Piercing",
    Weight: "3 lb",
    Properties: ["Ammunition", "Light", "Loading"],
  },
  {
    Name: "Crossbow, Heavy",
    Cost: "50 gp",
    Damage: "1d10 piercing",
    Damagetype: "Piercing",
    Weight: "18 lb",
    Properties: ["Ammunition", "Heavy", "Loading", "Two-Handed"],
  },
  {
    Name: "Crossbow, Light",
    Cost: "25 gp",
    Damage: "1d8 piercing",
    Damagetype: "Piercing",
    Weight: "5 lb",
    Properties: ["Ammunition", "Loading", "Two-Handed"],
  },
  {
    Name: "Shortbow",
    Cost: "25 gp",
    Damage: "1d6 piercing",
    Damagetype: "Piercing",
    Weight: "2 lb",
    Properties: ["Ammunition", "Light"],
  },
  {
    Name: "Composite Shortbow",
    Cost: "25 gp",
    Damage: "1d6 piercing",
    Damagetype: "Piercing",
    Weight: "2 lb",
    Properties: ["Ammunition", "Light"],
  },
  {
    Name: "Composite Longbow",
    Cost: "50 gp",
    Damage: "1d8 piercing",
    Damagetype: "Piercing",
    Weight: "2 lb",
    Properties: ["Ammunition", "Heavy", "Two-Handed"],
  },
  {
    Name: "Longbow",
    Cost: "50 gp",
    Damage: "1d8 piercing",
    Damagetype: "Piercing",
    Weight: "2 lb",
    Properties: ["Ammunition", "Heavy", "Two-Handed"],
  },
  {
    Name: "Dart",
    Cost: "5 cp",
    Damage: "1 piercing",
    Damagetype: "Piercing",
    Weight: "1/4 lb",
    Properties: ["Finesse", "Thrown (20/60)"],
  },
  {
    Name: "Javelin",
    Cost: "5 sp",
    Damage: "1d6 piercing",
    Damagetype: "Piercing",
    Weight: "2 lb",
    Properties: ["Thrown (30/120)"],
  },
  {
    Name: "Longbow",
    Cost: "50 gp",
    Damage: "1d8 piercing",
    Damagetype: "Piercing",
    Weight: "2 lb",
    Properties: ["Ammunition", "Heavy", "Two-Handed"],
  },
  {
    Name: "Net",
    Cost: "1 gp",
    Damage: "0",
    Damagetype: "Special",
    Weight: "3 lb",
    Properties: ["Special", "Thrown (5/15)"],
  },
  {
    Name: "Sling",
    Cost: "1 sp",
    Damage: "1d4 bludgeoning",
    Damagetype: "Bludgeoning",
    Weight: "0",
    Properties: ["Ammunition", "Light"],
  },
  {
    Name: "Bolas",
    Cost: "1 gp",
    Damage: "1d4 bludgeoning",
    Damagetype: "Bludgeoning",
    Weight: "2 lb",
    Properties: ["Special", "Thrown (20/60)"],
  },
  {
    Name: "Boomerang",
    Cost: "2 gp",
    Damage: "1d4 bludgeoning",
    Damagetype: "Bludgeoning",
    Weight: "1 lb",
    Properties: ["Special", "Thrown (20/60)"],
  },
];

const edgedEffects = [
  {
    name: "Flaming",
    type: "Burning",

    damage: "1d6",
    description: "The weapon deals an extra 1d6 fire damage on a hit.",
  },
  {
    name: "Frost",
    type: "Cold",
    damage: "1d6",
    description: "The weapon deals an extra 1d6 cold damage on a hit.",
  },
  {
    name: "Shock",
    type: "Electric",
    damage: "1d6",
    description: "The weapon deals an extra 1d6 lightning damage on a hit.",
  },
  {
    name: "Vicious",
    type: "Bleeding",
    damage: "1d6",
    description: "The weapon deals an extra 1d6 bleeding damage on a hit.",
  },
  {
    name: "Holy",

    type: "Radiant",
    damage: "1d6",
    description: "The weapon deals an extra 1d6 radiant damage on a hit.",
  },
  {
    name: "Unholy",
    type: "Necrotic",
    damage: "1d6",
    description: "The weapon deals an extra 1d6 necrotic damage on a hit.",
  },
  {
    name: "Keen",
    type: "Piercing",
    damage: "1d6",
    description: "The weapon deals an extra 1d6 piercing damage on a hit.",
  },
  {
    name: "Brutal",
    type: "Slashing",
    damage: "1d6",
    description: "The weapon deals an extra 1d6 slashing damage on a hit.",
  },
];

const bluntEffects = [
  {
    name: "Flaming",
    type: "Burning",

    damage: "1d6",
    description: "The weapon deals an extra 1d6 fire damage on a hit.",
  },
  {
    name: "Frost",
    type: "Cold",
    damage: "1d6",
    description: "The weapon deals an extra 1d6 cold damage on a hit.",
  },
  {
    name: "Shock",
    type: "Electric",
    damage: "1d6",
    description: "The weapon deals an extra 1d6 lightning damage on a hit.",
  },
  {
    name: "Holy",

    type: "Radiant",
    damage: "1d6",
    description: "The weapon deals an extra 1d6 radiant damage on a hit.",
  },
  {
    name: "Unholy",
    type: "Necrotic",
    damage: "1d6",
    description: "The weapon deals an extra 1d6 necrotic damage on a hit.",
  },
];

//This function will randomly select an effect from the arrays of effects and return it

//This function will randomly select a weapon from the arrays of weapons and return it
function randomWeapon() {
  let weapon = Math.floor(Math.random() * 3);

  const getEffect = (type) => {
    if (
      meleeWeapons.type ||
      randomWeapon === "Piercing" ||
      type === "Slashing"
    ) {
      return edgedEffects[Math.floor(Math.random() * edgedEffects.length)];
    } else if (meleeWeapons.type || randomWeapon === "Bludgeoning") {
      return bluntEffects[Math.floor(Math.random() * bluntEffects.length)];
    }
  };
  let effectType = getEffect();

  if (weapon === 0 || weapon === 1) {
    return meleeWeapons[Math.floor(Math.random() * meleeWeapons.length)];
  } else {
    return rangedWeapons[Math.floor(Math.random() * rangedWeapons.length)];
  }
}

export default randomWeapon;
